"""empty message

Revision ID: 8539de9c53b7
Revises: 966941a060db
Create Date: 2026-04-10 08:22:35.395840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8539de9c53b7'
down_revision = '966941a060db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commenter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comments_users', 'users', ['commenter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_users', type_='foreignkey')
        batch_op.drop_column('commenter_id')
    # ### end Alembic commands ###
