"""empty message

Revision ID: 966941a060db
Revises: 565223acddb4
Create Date: 2026-04-10 07:23:07.691928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966941a060db'
down_revision = '565223acddb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('posted')

    # ### end Alembic commands ###
